Repository ucoProject/UCO, pull requests merged in 2022-11, with the labels that each got.

#495 Issue 488: Fix typos for upstream design vocabularies
  ontology/co/co.ttl
  ontology/uco/observable/observable.ttl
Labels: bug

#500 Correct SHACL-SPARQL syntax of value selector
  ontology/owl/owl.ttl
Labels: bug

#503 Issue 502: Adjust SHACL-SPARQL sequence path queries to search for end
  ontology/owl/owl.ttl
  tests/shapes/examples_uco_owl/owl_shacl_paths_PASS.ttl
  tests/shapes/examples_uco_owl/owl_shacl_paths_PASS_validation.ttl
  tests/shapes/test_qc_shapes.py
Labels: bug

#475 UCO-415 Database Record Representation
  ontology/uco/observable/observable.ttl
  tests/examples/Makefile
  tests/examples/database_records_PASS.json
  tests/examples/database_records_PASS_validation.ttl
  tests/examples/database_records_XFAIL.json
  tests/examples/database_records_XFAIL_validation.ttl
  tests/examples/test_validation.py
Labels: Change Proposal

#505 Issue 504: Test monolithic build with SHACL-SHACL
  tests/Makefile
  tests/thing.ttl
Labels: Change Proposal

#490 Issue 487: Property Type Updates
  ontology/uco/observable/observable.ttl
Labels: bug

#492 Issue 491: Removal of errant concept owl:ontologyIRI
  ontology/co/co.ttl
  ontology/owl/owl.ttl
  ontology/uco/action/action.ttl
  ontology/uco/configuration/configuration.ttl
  ontology/uco/core/core.ttl
  ontology/uco/identity/identity.ttl
  ontology/uco/location/location.ttl
  ontology/uco/marking/marking.ttl
  ontology/uco/master/uco.ttl
  ontology/uco/observable/observable.ttl
  ontology/uco/pattern/pattern.ttl
  ontology/uco/role/role.ttl
  ontology/uco/time/time.ttl
  ontology/uco/tool/tool.ttl
  ontology/uco/types/types.ttl
  ontology/uco/victim/victim.ttl
  ontology/uco/vocabulary/vocabulary.ttl
  tests/shapes/examples_uco_owl/owl_incompatibleWith_shape_PASS.ttl
  tests/shapes/examples_uco_owl/owl_incompatibleWith_shape_PASS_validation.ttl
  tests/shapes/examples_uco_owl/owl_ontologyIRI_uniqueness_shape_PASS.ttl
  tests/shapes/examples_uco_owl/owl_ontologyIRI_uniqueness_shape_PASS_validation.ttl
  tests/shapes/examples_uco_owl/owl_ontologyIRI_versionIRI_prerequisite_shape_XFAIL.ttl
  tests/shapes/examples_uco_owl/owl_ontologyIRI_versionIRI_prerequisite_shape_XFAIL_validation.ttl
  tests/shapes/examples_uco_owl/owl_ontologyIRI_versionIRI_uniqueness_shape_PASS.ttl
  tests/shapes/examples_uco_owl/owl_ontologyIRI_versionIRI_uniqueness_shape_PASS_validation.ttl
  tests/shapes/examples_uco_owl/owl_versionIRI_multiversion_shape_PASS.ttl
  tests/shapes/examples_uco_qc/owl_Ontology_shape_property_owl_versionIRI_PASS.ttl
  tests/shapes/examples_uco_qc/owl_Ontology_shape_property_owl_versionIRI_XFAIL.ttl
  tests/shapes/examples_uco_qc/owl_Ontology_shape_sparql_imports_XFAIL.ttl
  tests/shapes/test_qc_shapes.py
Labels: bug

#497 Issue 400: Add new Analysis namespace and relevant classes-properties
  ontology/uco/analysis/analysis.ttl
  ontology/uco/master/uco.ttl
Labels: enhancement, Change Proposal
